# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
bodies = Body.create([{name: "sol", diameter: 1, color: 'ffcc00', x: 0, y: 0, z: 0, current: true, planet: 'planet', rings: false}, {name: "mercury", diameter: 0.2, color: 'aba9aa', x: 0, y: 0, z: 0, current: true, planet: 'planet', rings: false}, {name: "venus", diameter: 0.4, color: 'e0f7a6', x: 0, y: 0, z: 0, current: true, planet: 'planet', rings: false},
  {name: "earth", diameter: 0.4, color: '0077ff', x: 0, y: 0, z: 0, current: true, planet: 'planet', rings: false},
  {name: "mars", diameter: 0.3, color: 'd6965e', x: 0, y: 0, z: 0, current: true, planet: 'planet', rings: false},
  {name: "jupiter", diameter: 0.7, color: 'faa161', x: 0, y: 0, z: 0, current: true, planet: 'planet', rings: false},
  {name: "saturn", diameter: 0.5, color: 'd9ba73', x: 0, y: 0, z: 0, current: true, planet: 'planet', rings: true},
  {name: "uranus", diameter: 0.3, color: 'a7c2bd', x: 0, y: 0, z: 0, current: true, planet: 'planet', rings: true},
  {name: "neptune", diameter: 0.3, color: '829dd1', x: 0, y: 0, z: 0, current: true, planet: 'planet', rings: false},
  {:name=>"artemis-p1", :diameter=>0.5, :color=>"ffffff", :x=>0, :y=>0, :z=>0, :current=>true, planet: 'spacecraft', rings: false},
  {:name=>"newhorizons", :diameter=>0.5, :color=>"ffffff", :x=>0, :y=>0, :z=>0, :current=>true, planet: 'spacecraft', rings: false},
  {:name=>"artemis-p2", :diameter=>0.5, :color=>"ffffff", :x=>0, :y=>0, :z=>0, :current=>true, planet: 'spacecraft', rings: false},
  {:name=>"pioneer_10", :diameter=>0.5, :color=>"ffffff", :x=>0, :y=>0, :z=>0, :current=>true, planet: 'spacecraft', rings: false},
  {:name=>"cassini", :diameter=>0.3, :color=>"ffffff", :x=>0, :y=>0, :z=>0, :current=>true, planet: 'spacecraft', rings: false},
  {:name=>"pioneer_11", :diameter=>0.5, :color=>"ffffff", :x=>0, :y=>0, :z=>0, :current=>true, planet: 'spacecraft', rings: false},
  {:name=>"dawn", :diameter=>0.5, :color=>"ffffff", :x=>0, :y=>0, :z=>0, :current=>true, planet: 'spacecraft', rings: false},
  {:name=>"phobos_2", :diameter=>0.5, :color=>"ffffff", :x=>0, :y=>0, :z=>0, :current=>true, planet: 'spacecraft', rings: false},
  {:name=>"earth_(imp8,etc)", :diameter=>0.1, :color=>"ffffff", :x=>0, :y=>0, :z=>0, :current=>true, planet: 'spacecraft', rings: false},
  {:name=>"pluto", :diameter=>0.2, :color=>"a1b0c2", :x=>0, :y=>0, :z=>0, :current=>true, planet: 'planet', rings: false},
  {:name=>"galileo", :diameter=>0.2, :color=>"ffffff", :x=>0, :y=>0, :z=>0, :current=>true, planet: 'spacecraft', rings: false},
  {:name=>"rosetta", :diameter=>0.2, :color=>"ffffff", :x=>0, :y=>0, :z=>0, :current=>true, planet: 'spacecraft', rings: false},
  {:name=>"giotto", :diameter=>0.2, :color=>"ffffff", :x=>0, :y=>0, :z=>0, :current=>true, planet: 'spacecraft', rings: false},
  {:name=>"sakigake", :diameter=>0.2, :color=>"ffffff", :x=>0, :y=>0, :z=>0, :current=>true, planet: 'spacecraft', rings: false},
  {:name=>"helios_1", :diameter=>0.2, :color=>"ffffff", :x=>0, :y=>0, :z=>0, :current=>true, planet: 'spacecraft', rings: false},
  {:name=>"helios_2", :diameter=>0.2, :color=>"ffffff", :x=>0, :y=>0, :z=>0, :current=>true, planet: 'spacecraft', rings: false},
  {:name=>"stereoa", :diameter=>0.2, :color=>"ffffff", :x=>0, :y=>0, :z=>0, :current=>true, planet: 'spacecraft', rings: false},
  {:name=>"ice", :diameter=>0.2, :color=>"ffffff", :x=>0, :y=>0, :z=>0, :current=>true, planet: 'spacecraft', rings: false},
  {:name=>"stereob", :diameter=>0.2, :color=>"ffffff", :x=>0, :y=>0, :z=>0, :current=>true, planet: 'spacecraft', rings: false},
  {:name=>"ice_return", :diameter=>0.2, :color=>"ffffff", :x=>0, :y=>0, :z=>0, :current=>true, planet: 'spacecraft', rings: false},
  {:name=>"suisei", :diameter=>0.2, :color=>"ffffff", :x=>0, :y=>0, :z=>0, :current=>true, planet: 'spacecraft', rings: false},
  {:name=>"ulysses", :diameter=>0.2, :color=>"ffffff", :x=>0, :y=>0, :z=>0, :current=>true, planet: 'spacecraft', rings: false},
  {:name=>"venus_(pvo)", :diameter=>0.2, :color=>"ffffff", :x=>0, :y=>0, :z=>0, :current=>true, planet: 'spacecraft', rings: false},
  {:name=>"voyager_1", :diameter=>0.2, :color=>"ffffff", :x=>0, :y=>0, :z=>0, :current=>true, planet: 'spacecraft', rings: false},
  {:name=>"voyager_2", :diameter=>0.2, :color=>"ffffff", :x=>0, :y=>0, :z=>0, :current=>true, planet: 'spacecraft', rings: false},
  {:name=>"messenger", :diameter=>0.2, :color=>"ffffff", :x=>0, :y=>0, :z=>0, :current=>true, planet: 'spacecraft', rings: false},
  {:name=>"comet_grigg-skjlp", :diameter=>0.2, :color=>"ffffff", :x=>0, :y=>0, :z=>0, :current=>true, planet: 'spacecraft', rings: false},
  {:name=>"comet_borrelly", :diameter=>0.2, :color=>"ffffff", :x=>0, :y=>0, :z=>0, :current=>true, planet: 'spacecraft', rings: false},
  {:name=>"comet_h-m-p", :diameter=>0.2, :color=>"ffffff", :x=>0, :y=>0, :z=>0, :current=>true, planet: 'spacecraft', rings: false},
  {:name=>"comet_wild_2", :diameter=>0.2, :color=>"ffffff", :x=>0, :y=>0, :z=>0, :current=>true, planet: 'spacecraft', rings: false},
  {:name=>"comet_hale-bopp", :diameter=>0.2, :color=>"ffffff", :x=>0, :y=>0, :z=>0, :current=>true, planet: 'spacecraft', rings: false},
  {:name=>"comet_hyakutake", :diameter=>0.2, :color=>"ffffff", :x=>0, :y=>0, :z=>0, :current=>true, planet: 'spacecraft', rings: false},
  {:name=>"comet_halley", :diameter=>0.2, :color=>"ffffff", :x=>0, :y=>0, :z=>0, :current=>true, planet: 'spacecraft', rings: false},
  {:name=>"comet_giacobini-zinner", :diameter=>0.2, :color=>"ffffff", :x=>0, :y=>0, :z=>0, :current=>true, planet: 'spacecraft', rings: false}])