# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
bodies = Body.create([{name: "sol", diameter: 1, color: 'ffcc00', x: 0, y: 0, z: 0, current: true, planet: 'planet', rings: false, nice_name: "Sun"}, {name: "mercury", diameter: 0.2, color: 'aba9aa', x: 0, y: 0, z: 0, current: true, planet: 'planet', rings: false, nice_name: "Mercury"}, {name: "venus", diameter: 0.4, color: 'e0f7a6', x: 0, y: 0, z: 0, current: true, planet: 'planet', rings: false, nice_name: "Venus"},
  {name: "earth", diameter: 0.4, color: '0077ff', x: 0, y: 0, z: 0, current: true, planet: 'planet', rings: false, nice_name: "Earth"},
  {name: "mars", diameter: 0.3, color: 'd6965e', x: 0, y: 0, z: 0, current: true, planet: 'planet', rings: false, nice_name: "Mars"},
  {name: "jupiter", diameter: 0.7, color: 'faa161', x: 0, y: 0, z: 0, current: true, planet: 'planet', rings: false, nice_name: "Jupiter"},
  {name: "saturn", diameter: 0.5, color: 'd9ba73', x: 0, y: 0, z: 0, current: true, planet: 'planet', rings: true, nice_name: "Saturn"},
  {name: "uranus", diameter: 0.3, color: 'a7c2bd', x: 0, y: 0, z: 0, current: true, planet: 'planet', rings: true, nice_name: "Uranus"},
  {name: "neptune", diameter: 0.3, color: '829dd1', x: 0, y: 0, z: 0, current: true, planet: 'planet', rings: false, nice_name: "Neptune"},
  {:name=>"artemis-p1", :diameter=>0.5, :color=>"ffffff", :x=>0, :y=>0, :z=>0, :current=>true, planet: 'spacecraft', rings: false, nice_name: 'ARTEMIS'},
  {:name=>"newhorizons", :diameter=>0.5, :color=>"ffffff", :x=>0, :y=>0, :z=>0, :current=>true, planet: 'spacecraft', rings: false, nice_name: "New_Horizons"},
  {:name=>"artemis-p2", :diameter=>0.5, :color=>"ffffff", :x=>0, :y=>0, :z=>0, :current=>true, planet: 'spacecraft', rings: false, nice_name: "ARTEMIS"},
  {:name=>"pioneer_10", :diameter=>0.5, :color=>"ffffff", :x=>0, :y=>0, :z=>0, :current=>true, planet: 'spacecraft', rings: false, nice_name: "Pioneer_10"},
  {:name=>"cassini", :diameter=>0.3, :color=>"ffffff", :x=>0, :y=>0, :z=>0, :current=>true, planet: 'spacecraft', rings: false, nice_name: "Cassini"},
  {:name=>"pioneer_11", :diameter=>0.5, :color=>"ffffff", :x=>0, :y=>0, :z=>0, :current=>true, planet: 'spacecraft', rings: false, nice_name: "Pioneer_11"},
  {:name=>"dawn", :diameter=>0.5, :color=>"ffffff", :x=>0, :y=>0, :z=>0, :current=>true, planet: 'spacecraft', rings: false, nice_name: "DAWN"},
  {:name=>"phobos_2", :diameter=>0.5, :color=>"ffffff", :x=>0, :y=>0, :z=>0, :current=>true, planet: 'spacecraft', rings: false, nice_name: "Phobos_2"},
  {:name=>"earth_(imp8,etc)", :diameter=>0.1, :color=>"ffffff", :x=>0, :y=>0, :z=>0, :current=>true, planet: 'spacecraft', rings: false, nice_name: 'IMP8'},
  {:name=>"pluto", :diameter=>0.2, :color=>"a1b0c2", :x=>0, :y=>0, :z=>0, :current=>true, planet: 'planet', rings: false, nice_name: "Pluto"},
  {:name=>"galileo", :diameter=>0.2, :color=>"ffffff", :x=>0, :y=>0, :z=>0, :current=>true, planet: 'spacecraft', rings: false, nice_name: 'Galileo_Spacecraft'},
  {:name=>"rosetta", :diameter=>0.2, :color=>"ffffff", :x=>0, :y=>0, :z=>0, :current=>true, planet: 'spacecraft', rings: false, nice_name:"Rosetta"},
  {:name=>"giotto", :diameter=>0.2, :color=>"ffffff", :x=>0, :y=>0, :z=>0, :current=>true, planet: 'spacecraft', rings: false, nice_name: "Giotto"},
  {:name=>"sakigake", :diameter=>0.2, :color=>"ffffff", :x=>0, :y=>0, :z=>0, :current=>true, planet: 'spacecraft', rings: false, nice_name: 'Sakigake'},
  {:name=>"helios_1", :diameter=>0.2, :color=>"ffffff", :x=>0, :y=>0, :z=>0, :current=>true, planet: 'spacecraft', rings: false, nice_name: 'Helios_1'},
  {:name=>"helios_2", :diameter=>0.2, :color=>"ffffff", :x=>0, :y=>0, :z=>0, :current=>true, planet: 'spacecraft', rings: false, nice_name: 'Helios_2'},
  {:name=>"stereoa", :diameter=>0.2, :color=>"ffffff", :x=>0, :y=>0, :z=>0, :current=>true, planet: 'spacecraft', rings: false, nice_name: "Stereo_A"},
  {:name=>"ice", :diameter=>0.2, :color=>"ffffff", :x=>0, :y=>0, :z=>0, :current=>true, planet: 'spacecraft', rings: false, nice_name: "ISEE-3"},
  {:name=>"stereob", :diameter=>0.2, :color=>"ffffff", :x=>0, :y=>0, :z=>0, :current=>true, planet: 'spacecraft', rings: false, nice_name: "Stereo_B"},
  {:name=>"ice_return", :diameter=>0.2, :color=>"ffffff", :x=>0, :y=>0, :z=>0, :current=>true, planet: 'spacecraft', rings: false, nice_name: "ISEE-3"},
  {:name=>"suisei", :diameter=>0.2, :color=>"ffffff", :x=>0, :y=>0, :z=>0, :current=>true, planet: 'spacecraft', rings: false, nice_name: "Suisei"},
  {:name=>"ulysses", :diameter=>0.2, :color=>"ffffff", :x=>0, :y=>0, :z=>0, :current=>true, planet: 'spacecraft', rings: false, nice_name: 'Ulysses'},
  {:name=>"venus_(pvo)", :diameter=>0.2, :color=>"ffffff", :x=>0, :y=>0, :z=>0, :current=>true, planet: 'spacecraft', rings: false, nice_name: 'Pioneer_Venus_Orbiter'},
  {:name=>"voyager_1", :diameter=>0.2, :color=>"ffffff", :x=>0, :y=>0, :z=>0, :current=>true, planet: 'spacecraft', rings: false, nice_name: 'Voyager_1'},
  {:name=>"voyager_2", :diameter=>0.2, :color=>"ffffff", :x=>0, :y=>0, :z=>0, :current=>true, planet: 'spacecraft', rings: false, nice_name: 'Voyager_2'},
  {:name=>"messenger", :diameter=>0.2, :color=>"ffffff", :x=>0, :y=>0, :z=>0, :current=>true, planet: 'spacecraft', rings: false, nice_name: 'Messenger'},
  {:name=>"comet_grigg-skjlp", :diameter=>0.2, :color=>"ffffff", :x=>0, :y=>0, :z=>0, :current=>true, planet: 'spacecraft', rings: false, nice_name: 'Comet_Grigg-Skjellerup'},
  {:name=>"comet_borrelly", :diameter=>0.2, :color=>"ffffff", :x=>0, :y=>0, :z=>0, :current=>true, planet: 'spacecraft', rings: false, nice_name: 'Comet_Borrelly'},
  {:name=>"comet_h-m-p", :diameter=>0.2, :color=>"ffffff", :x=>0, :y=>0, :z=>0, :current=>true, planet: 'spacecraft', rings: false, nice_name: 'Comet_Honda-Mrkos-Pajdusakova'},
  {:name=>"comet_wild_2", :diameter=>0.2, :color=>"ffffff", :x=>0, :y=>0, :z=>0, :current=>true, planet: 'spacecraft', rings: false, nice_name: 'Comet_Wild_2'},
  {:name=>"comet_hale-bopp", :diameter=>0.2, :color=>"ffffff", :x=>0, :y=>0, :z=>0, :current=>true, planet: 'spacecraft', rings: false, nice_name: 'Comet_Hale-Bopp'},
  {:name=>"comet_hyakutake", :diameter=>0.2, :color=>"ffffff", :x=>0, :y=>0, :z=>0, :current=>true, planet: 'spacecraft', rings: false, nice_name: 'Comet_Hyakutake'},
  {:name=>"comet_halley", :diameter=>0.2, :color=>"ffffff", :x=>0, :y=>0, :z=>0, :current=>true, planet: 'spacecraft', rings: false, nice_name: 'Comet_Halley'},
  {:name=>"comet_giacobini-zinner", :diameter=>0.2, :color=>"ffffff", :x=>0, :y=>0, :z=>0, :current=>true, planet: 'spacecraft', rings: false, nice_name: 'Comet_Giacobini-Zinner'}])